### ISSUE TITLE
Can we please get an update to the latest patch?

### ISSUE THREAD

**Issue by gdragon-git** [bonesbro/ValFloorsAreRoofs#2]
Pretty please? For v0.217.24 patch.
Thunderstore upload, too, please!

**Comment by bonesbro** [comment]
Are you getting any errors with the current patch?  If so, could you please provide the error from the log?

**Comment by gdragon-git** [comment]
Ah I didn't test yet. Was putting together a pack and was told that any mod not updated wouldn't work. If you see it working then that's good enough for me. Sorry for the bother.

**Comment by bonesbro** [comment]
No problem - and if you do see any problems I'd be happy to investigate and fix them.
